apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-mongo
  template:
    metadata:
      labels:
        app: posts-mongo
    spec:
      volumes:
        - name: posts-mongodb-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim-mongodb-posts
      containers:
        - name: posts-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: posts-mongodb-storage
              mountPath: /data/db
              subPath: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: posts-mongo-srv
spec:
  selector:
    app: posts-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
