apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts2-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts2
  template:
    metadata:
      labels:
        app: posts2
    spec:
      containers:
        - name: posts2
          image: stanley158831384/posts2
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://posts2-mongo-srv:27017/posts2"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: posts2-srv
spec:
  selector:
    app: posts2
  ports:
    - name: posts2
      protocol: TCP
      port: 3000
      targetPort: 3000
