apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketsex-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketsex
  template:
    metadata:
      labels:
        app: ticketsex
    spec:
      containers:
        - name: ticketsex
          image: stanley158831384/ticketsex
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://ticketsex-mongo-srv:27017/ticketsex"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketsex-srv
spec:
  selector:
    app: ticketsex
  ports:
    - name: ticketsex
      protocol: TCP
      port: 3000
      targetPort: 3000
